# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2ed002f8-05fa-4fb6-b30a-7f2eea33d737";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A02D-A7AE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a0ac67b4-b1e8-4eb0-b865-5f8ab7d69767"; }
    ];

  fileSystems."/mnt/b" = {
    device = "/dev/disk/by-uuid/9b5bc326-530b-481f-b6a8-e56ea2aefaf0";
    fsType = "ext4";
    options = [ "noatime" ];
   };

  fileSystems."/mnt/a" = {
    device = "/dev/disk/by-uuid/6c8e516a-dccf-464b-895e-e3645f4e8613";
    fsType = "xfs";
    options = [ "noatime" ];
   };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
